# Generated by Django 5.1.6 on 2025-02-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('mx_records', models.JSONField(blank=True, default=list)),
                ('mail_status', models.CharField(blank=True, max_length=50, null=True)),
                ('mail_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('data', models.JSONField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteScrapingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('pagination_enabled', models.BooleanField(default=False)),
                ('scraping_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DomainEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.domaindata')),
            ],
        ),
        migrations.CreateModel(
            name='DomainNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='core.domaindata')),
            ],
        ),
        migrations.CreateModel(
            name='DomainSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_link', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.domaindata')),
            ],
        ),
        migrations.AddField(
            model_name='domaindata',
            name='website_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.websitescrapingstatus'),
        ),
    ]
