# Generated by Django 5.1.6 on 2025-03-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables_data', models.JSONField()),
                ('raw_data', models.TextField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('pagination_enabled', models.BooleanField(default=False)),
                ('scraping_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('social_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_entries', to='api.rawdata')),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to='api.urldata')),
            ],
        ),
        migrations.AddField(
            model_name='rawdata',
            name='url_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='api.urldata'),
        ),
        migrations.CreateModel(
            name='DomainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('emails', models.JSONField(default=list)),
                ('phone_numbers', models.JSONField(default=list)),
                ('social_media_links', models.JSONField(default=list)),
                ('mx_records', models.TextField()),
                ('mail_provider', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='api.urldata')),
            ],
        ),
    ]
