# Generated by Django 5.1.6 on 2025-03-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaindata',
            name='mail_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='domaindata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domaindata',
            name='mail_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domaindata',
            name='mx_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='domaindata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
