# Generated by Django 5.1.6 on 2025-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_domaindata_mail_status_alter_domaindata_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='raw_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='tables_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
