# Generated by Django 5.1.6 on 2025-03-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rawdata_raw_data_alter_rawdata_tables_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
